let mapleader=" "

set showcmd 
set scrolloff=8
set number
set rnu
set termguicolors
set path+=**
syntax enable
filetype plugin on
filetype plugin indent on
colorscheme diov
set bg=dark
set tabstop=4 softtabstop=4
set smartindent
set expandtab
set shiftwidth=4
set incsearch
set makeprg=gcc\ -o\ run\ %;./run
"set t_Co=256
"set foldmethod=indent
"set foldlevel=1
"set foldclose=all

"set undofile
"set undodir=~/.cache/vim/undo
"set undolevels=1000
"set undoreload=3000

nnoremap <leader><cr> :so ~/.config/vim/vimrc<cr>
nnoremap <leader>Y mmggVG:w ! xclip -selection clipboard<cr><cr>`mzz
vnoremap <leader>y :w ! xclip -selection clipboard<cr><cr>
vnoremap <leader>p "_dP

"nnoremap <leader>v :Vex<cr>
"nnoremap <leader>s :Sex<cr>
"nnoremap <leader>p :Exp<cr>
"nnoremap <leader>tt :term<cr>

nnoremap 6b :b 6<cr>
nnoremap <c-k> :bnext<cr>
nnoremap <c-j> :bprev<cr>
nnoremap <leader>ls :ls<cr>

nnoremap <leader><c-p> :copen<cr>
nnoremap <leader><c-k> :cnext<cr>
nnoremap <leader><c-j> :cprev<cr>
nnoremap <leader>m :w<cr>:make<cr>

nnoremap <c-p> gT
nnoremap <c-n> gt

nnoremap <c-d> <c-d>zz
nnoremap <c-u> <c-u>zz
nnoremap <c-f> <c-f>zz
nnoremap <c-b> <c-b>zz
nnoremap G GGzz

nnoremap [<leader> mmo<esc>xx`mh " xx: some issue with D
nnoremap ]<leader> mmO<esc>xx`mh

nnoremap <leader>w :w<cr>
nnoremap <leader>W :wq<cr>
nnoremap <leader>q :q!<cr>
nnoremap <leader>; :<c-f>i

"noremap H ^
"nnoremap L $
"nnoremap dH d^
"nnoremap dL d$
"vnoremap H ^
"vnoremap L $

vnoremap <leader>c :s/\(.*\)/\/\/ \1<cr>
vnoremap <leader>u :s/\/\/ \(.*\)/\1<cr>

ia <! <esc>:0r ~/languages/web/html/template.html<cr>/body<cr>o<cr><esc>Vkc

" gd - go to declaration of local variable under the cursor
" gi
" gg=G fix indentation of whole file
"
" use w, W, b, B, e, E, ge, gE
"
" # - find next occurence of word under cursor backwards
" * - find next occurence of word under cursor forward
"
" Move cursor relative to visible area of window
" H - high
" M - mid
" L - low
"
" position the screen with the cursor at:
" zt - top
" zb - bottom
